export enum OpTypeEnum {
  IN = 'in',
  EXACT_MATCH = 'exact_match',
  ANY_EXACT_MATCH = 'any_exact_match',
  FUZZY_MATCH = 'fuzzy_match',
  ANY_FUZZY_MATCH = 'any_fuzzy_match',
  GT = 'gt',
  GE = 'ge',
  LT = 'lt',
  LE = 'le',
  EQ = 'eq',
  NE = 'ne',
  CLOSE_INTERVAL = 'close_interval',
  OPEN_INTERVAL = 'open_interval',
  LO_RC_INTERVAL = 'lo_rc_interval',
  LC_RO_INTERVAL = 'lc_ro_interval',
  UNLIMITED = 'unlimited',
  COMPOSE = 'compose',
  EXACT_EXCLUDE = 'exact_exclude',
  FUZZY_EXCLUDE = 'fuzzy_exclude',
}

export const OpTypeDesc = {
  [OpTypeEnum.IN]: '包含',
  [OpTypeEnum.EXACT_MATCH]: '精确匹配',
  [OpTypeEnum.FUZZY_MATCH]: '模糊匹配',
  [OpTypeEnum.ANY_EXACT_MATCH]: '精确匹配',
  [OpTypeEnum.ANY_FUZZY_MATCH]: '模糊匹配',
  [OpTypeEnum.GT]: '>',
  [OpTypeEnum.GE]: '>=',
  [OpTypeEnum.LT]: '<',
  [OpTypeEnum.LE]: '<=',
  [OpTypeEnum.EQ]: '=',
  [OpTypeEnum.NE]: '!=',
  [OpTypeEnum.CLOSE_INTERVAL]: '闭区间',
  [OpTypeEnum.OPEN_INTERVAL]: '开区间',
  [OpTypeEnum.LO_RC_INTERVAL]: '左开右闭',
  [OpTypeEnum.LC_RO_INTERVAL]: '左闭右开',
  [OpTypeEnum.UNLIMITED]: '不限',
  [OpTypeEnum.COMPOSE]: '组合',
  [OpTypeEnum.EXACT_EXCLUDE]: '精确排除',
  [OpTypeEnum.FUZZY_EXCLUDE]: '模糊排除',
}
