/** 用于维护所有字段的映射 */
export enum FieldOptionIds {
  /** 选择操作-追加商家 */
  AppendPoi = 'appendPoi',
  AppendPoiOfEdit = 'appendPoiOfEdit',
  /** 选择操作-限制 */
  LimitOption = 'limitOption',
  NoLimitOption = 'noLimitOption',
  NoOperation = 'noOperation',
  NoOperationOfEdit = 'noOperationOfEdit',
  NoOperationOfSettings = 'noOperationOfSettings',
  RemovePoi = 'removePoi',
  RemovePoiOfEdit = 'removePoiOfEdit',
  ReplaceAll = 'replaceAll',
  ReplaceAllOfEdit = 'replaceAllOfEdit',
  ByFilter = 'byFilter',
  ByFilterOfEdit = 'byFilterOfEdit',
  ByIdOption = 'byIdOption',
  ByUpload = 'byUpload',
  ByConditionFilter = 'byConditionFilter',
  ByMerchantBrand = 'byMerchantBrand',
  ByPoiInviteOption = 'byPoiInviteOption',
  ActTimeNoLimit = 'actTimeNoLimit',
  ActTimeLimit = 'actTimeLimit',
  DirectMtCharge = 'directMtCharge',
  AgentMtCharge = 'agentMtCharge',
  BrandCharge = 'brandCharge',
  NeedOtherCharge = 'needOtherCharge',
}

export const FieldOptionIdsText: Record<FieldOptionIds, string> = {
  [FieldOptionIds.AppendPoi]: '选择操作-追加商家',
  [FieldOptionIds.LimitOption]: '选择操作-限制',
  [FieldOptionIds.NoLimitOption]: '选择操作-不限制',
  [FieldOptionIds.NoOperation]: '选择操作-不操作',
  [FieldOptionIds.RemovePoi]: '选择操作-删除商家',
  [FieldOptionIds.ReplaceAll]: '选择操作-替换商家',
  [FieldOptionIds.ByFilter]: '录入方式-通过条件筛选',
  [FieldOptionIds.ByIdOption]: '录入方式-录入 ID',
  [FieldOptionIds.ByUpload]: '录入方式-上传 xls/xlsx',
  [FieldOptionIds.ByConditionFilter]: '邀请方式-根据条件筛选商家',
  [FieldOptionIds.ByMerchantBrand]: '邀请方式-通过业务品牌邀请',
  [FieldOptionIds.ByPoiInviteOption]: '邀请方式-通过门店邀请',
  [FieldOptionIds.AppendPoiOfEdit]: '【编辑场景】选择操作-追加商家',
  [FieldOptionIds.NoOperationOfEdit]: '【编辑场景】选择操作-不操作',
  [FieldOptionIds.RemovePoiOfEdit]: '【编辑场景】选择操作-删除商家',
  [FieldOptionIds.ReplaceAllOfEdit]: '【编辑场景】选择操作-替换',
  [FieldOptionIds.ByFilterOfEdit]: '【编辑场景】邀请方式-通过条件筛选',
  [FieldOptionIds.NoOperationOfSettings]: '【邀请设置场景】选择操作-不操作',
  [FieldOptionIds.ActTimeNoLimit]: '生效时间-不限制',
  [FieldOptionIds.ActTimeLimit]: '生效时间-限制',
  [FieldOptionIds.DirectMtCharge]: '直营门店美补',
  [FieldOptionIds.AgentMtCharge]: '代理门店美补',
  [FieldOptionIds.BrandCharge]: '品牌补贴',
  [FieldOptionIds.NeedOtherCharge]: '需要其他补贴方',
}
