/** 用于维护所有字段的映射 */
export enum FieldIds {
  /** CRUD 选择操作 */
  ChooseOperation = 'chooseOperation',
  ChooseOperationOfEdit = 'chooseOperationOfEdit',
  /** 邀请设置选择操作 */
  ChooseOperationOfSettings = 'chooseOperationOfSettings',
  UploadId = 'uploadId',
  FilterRule = 'filterRule',
  InputId = 'inputId',
  InputIdsWay = 'inputIdsWay',
  BelongBizline = 'belongBizline',
  InputIdsWayOfEdit = 'inputIdsWayOfEdit',
  InputIdsWayOfView = 'inputIdsWayOfView',
  InviteWay = 'inviteWay',
  InviteWayOfEdit = 'inviteWayOfEdit',
  PoiList = 'poiList',
  PoiListOfSettings = 'poiListOfSettings',
  ActIdOfSettings = 'actIdOfSettings',
  ActNameOfSettings = 'actNameOfSettings',
  ActStatusOfSettings = 'actStatusOfSettings',
  Qualify = 'qualify',
  DisSubActName = 'disSubActName',
  CanApplyGoodCount = 'canApplyGoodCount',
  CanApplyActCount = 'canApplyActCount',
  DiscountRange = 'discountRange',
  DisChargeType = 'disChargeType',
  PriceRange = 'priceRange',

  ActRule = 'actRule',

  /** 活动生效时间 */
  ActTime = 'actTime',
  ActTimeRange = 'actTimeRange',
  /** 商家报名截止时间 */
  EndTime = 'endTime',
  /** 周循环 */
  WeekDays = 'weekDays',
  /** 活动简介 */
  ActDesc = 'actDesc',
  /** 活动名称 */
  ActName = 'actName',
  /** 补贴类型 */
  ChargeFlowType = 'chargeFlowType',
  SubsidyChargeFlowType = 'subsidyChargeFlowType',
  /** 门店类型 */
  PoiType = 'poiType',
  /** 促销类型 */
  PromotionType = 'promotionType',
  /** 活动规则 */
  RuleDesc = 'ruleDesc',
  /** 预算申请理由 */
  ApplyReasonField = 'applyReasonField',
  /** 补贴分摊-预算金额 */
  BudgetAmount = 'budgetAmount',
  /** 补贴分摊-强弱管控 */
  PnControl = 'pnControl',
  /** 补贴分摊-承担组织 */
  Pn = 'pn',
  MtSubsidyField = 'mtsubsidyField',
  AgentSubsidyField = 'agentSubsidyField',
  MerchantSubsidyField = 'merchantsubsidyField',
  ChargeSidePn = 'chargeSidePn',
  CanApplyRole = 'canApplyRole',
  CanCancelAct = 'canCancelAct',
  CanEditAct = 'canEditAct',
  CanEditGoodInfo = 'canEditGoodInfo',
  CanAudit = 'canAudit',
  InviteTips = 'inviteTips',
  InvitationTips = 'invitationTips',
  TargetCollectStoreField = 'targetCollectStoreField',
}

export const FieldIdsText: Record<FieldIds, string> = {
  [FieldIds.ChooseOperation]: 'CRUD 选择操作',
  [FieldIds.ChooseOperationOfSettings]: '邀请设置选择操作',
  [FieldIds.UploadId]: '邀请设置-上传 ID',
  [FieldIds.FilterRule]: '邀请设置-关联供给筛选集',
  [FieldIds.InputId]: '邀请设置-输入 ID',
  [FieldIds.InputIdsWay]: '邀请设置-录入方式',
  [FieldIds.InviteWay]: '邀请设置-邀请方式',
  [FieldIds.PoiList]: '邀请设置-门店列表',
  [FieldIds.InputIdsWayOfEdit]: '【编辑场景】录入方式',
  [FieldIds.InviteWayOfEdit]: '【编辑场景】邀请方式',
  [FieldIds.ChooseOperationOfEdit]: '【编辑场景】邀请设置固定模块',
  [FieldIds.PoiListOfSettings]: '【邀请设置场景】门店列表',
  [FieldIds.ActIdOfSettings]: '【邀请设置场景】活动 ID',
  [FieldIds.ActNameOfSettings]: '【邀请设置场景】活动名称',
  [FieldIds.ActStatusOfSettings]: '【邀请设置场景】活动状态',
  [FieldIds.Qualify]: '报名资质',
  [FieldIds.DisSubActName]: '折扣活动子活动名称',
  [FieldIds.CanApplyGoodCount]: '可报名商品数',
  [FieldIds.CanApplyActCount]: '可报名优惠活动数',
  [FieldIds.DiscountRange]: '折扣范围',
  [FieldIds.PriceRange]: '价格范围',
  [FieldIds.ActTime]: '活动生效时间',
  [FieldIds.EndTime]: '商家报名截止时间',
  [FieldIds.WeekDays]: '周循环',
  [FieldIds.ActDesc]: '活动简介',
  [FieldIds.ActName]: '活动名称',
  [FieldIds.ChargeFlowType]: '补贴类型',
  [FieldIds.PoiType]: '门店类型',
  [FieldIds.PromotionType]: '促销类型',
  [FieldIds.RuleDesc]: '活动规则',
  [FieldIds.ApplyReasonField]: '预算申请理由',
  [FieldIds.BudgetAmount]: '补贴分摊-预算金额',
  [FieldIds.PnControl]: '补贴分摊-强弱管控',
  [FieldIds.Pn]: '补贴分摊-承担组织',
  [FieldIds.BelongBizline]: '所属业务线',
  [FieldIds.MtSubsidyField]: '补贴分担-美团承担',
  [FieldIds.MerchantSubsidyField]: '补贴分担-商家承担',
  [FieldIds.ChargeSidePn]: '承担组织',
  [FieldIds.CanApplyRole]: '可报名角色',
  [FieldIds.CanCancelAct]: '可取消活动',
  [FieldIds.CanEditAct]: '可编辑活动',
  [FieldIds.CanEditGoodInfo]: '可编辑商品信息',
  [FieldIds.CanAudit]: '审核报名结果',
  [FieldIds.InviteTips]: '【闪购】邀请提示',
  [FieldIds.InvitationTips]: '活动邀请-下方提示语',
  [FieldIds.ActTimeRange]: '活动生效时间范围',
  [FieldIds.TargetCollectStoreField]: '目标集合店',
  [FieldIds.ActRule]: '设置规则',
  [FieldIds.SubsidyChargeFlowType]: '补贴分担-补贴类型',
  [FieldIds.InputIdsWayOfView]: '【查看】录入方式',
  [FieldIds.DisChargeType]: '补贴类型',
  [FieldIds.AgentSubsidyField]: '代理商承担',
}
