export enum ConfigId {
  ActType = 'actType',
  PlanType = 'planType',
  Env = 'env',
  WhiteList = 'whiteList',
  ResourceIdList = 'resourceIdList',
  ActCopyAuths = 'actCopyAuths',
  ActEditAuths = 'actEditAuths',
  ActInviteSettingsAuths = 'actInviteSettingsAuths',
  ActSendInviteAuths = 'actSendInviteAuths',
  ActWithdrawAuths = 'actWithdrawAuths',
  PlanEditBtnAuths = 'planEditBtnAuths',
  PlanCopyBtnAuths = 'planCopyBtnAuths',
  ActPoiConfirmAuths = 'actPoiConfirmAuths',
  AuthPlanOptionsInfo = 'authPlanOptionsInfo',
  AuthActOptionsInfo = 'authActOptionsInfo',
  ShowPublishPlanBtn = 'showPublishPlanBtn',
  ShowPlanSendInviteBtn = 'showPlanSendInviteBtn',
  ShowJoinPlanBtn = 'showJoinPlanBtn',
  ShowPlanApplyResultBtn = 'showPlanApplyResultBtn',
  ShowPlanWithdrawBtn = 'showPlanWithdrawBtn',
  ShowPlanCopyBtn = 'showPlanCopyBtn',
  ShowPlanEditBtn = 'showPlanEditBtn',
  ShowActCopyBtn = 'showActCopyBtn',
  ShowActEditBtn = 'showActEditBtn',
  ShowConfirmAgreement = 'showConfirmAgreement',
  ShowConfirmSku = 'showConfirmSku',
  UsePlanSendInviteDefaultAction = 'usePlanSendInviteDefaultAction',
  UsePlanWithdrawDefaultAction = 'usePlanWithdrawDefaultAction',
  UsePlanViewDefaultAction = 'usePlanViewDefaultAction',
  ShowActInviteSettingsBtn = 'showActInviteSettingsBtn',
  ShowActProgressBtn = 'showActProgressBtn',
  ShowActPoiConfirmBtn = 'showActPoiConfirmBtn',
  NeedCheckGray = 'needCheckGray',
  ApplyDefaultRole = 'applyDefaultRole',
  ActFactorInfo = 'actFactorInfo',
  TemplateInfo = 'templateInfo',
  UseNewFrameworkApplyResPage = 'useNewFrameworkApplyResPage',
  UseNewZsptFramework = 'useNewZsptFramework',
  DisableNoLimitOption = 'disableNoLimitOption',
  DisableMerchantBrandOption = 'disableMerchantBrandOption',
  ShowInputWayOfInviteSettingsByMerchantOp = 'showInputWayOfInviteSettingsByMerchantOp',
}

export const ConfigIdText: Record<ConfigId, string> = {
  [ConfigId.ResourceIdList]: '补贴资源',
  [ConfigId.ActCopyAuths]: '活动复制按钮权限',
  [ConfigId.ActEditAuths]: '活动编辑按钮权限',
  [ConfigId.ActPoiConfirmAuths]: '活动合作运营确认按钮权限',
  [ConfigId.ActInviteSettingsAuths]: '活动邀请设置按钮权限',
  [ConfigId.ActSendInviteAuths]: '活动发送邀请按钮权限',
  [ConfigId.ActWithdrawAuths]: '活动撤回按钮权限',
  [ConfigId.ShowActCopyBtn]: '展示活动复制按钮',
  [ConfigId.ShowActEditBtn]: '展示活动编辑按钮',
  [ConfigId.ShowActPoiConfirmBtn]: '展示合作运营确认按钮',
  [ConfigId.ShowActInviteSettingsBtn]: '展示活动邀请设置按钮',
  [ConfigId.ShowConfirmAgreement]: '展示确认协议按钮',
  [ConfigId.ShowConfirmSku]: '展示确认商品按钮',
  [ConfigId.ShowActProgressBtn]: '展示活动进度按钮',
  [ConfigId.ActFactorInfo]: '因子信息',
  [ConfigId.DisableNoLimitOption]: '禁用「选择操作-不限制」选项',
  [ConfigId.DisableMerchantBrandOption]: '禁用「通过商家品牌邀请」选项',
  [ConfigId.ShowInputWayOfInviteSettingsByMerchantOp]:
    '通过商家品牌邀请的情况下，是否展示录入方式',
  [ConfigId.TemplateInfo]: '模板信息',
  [ConfigId.ActType]: '活动类型',
  [ConfigId.PlanEditBtnAuths]: '方案编辑按钮权限',
  [ConfigId.PlanCopyBtnAuths]: '方案复制按钮权限',
  [ConfigId.AuthPlanOptionsInfo]: '方案操作授权选项',
  [ConfigId.AuthActOptionsInfo]: '活动操作授权选项',
  [ConfigId.ShowPublishPlanBtn]: '展示发布方案按钮',
  [ConfigId.ShowPlanSendInviteBtn]: '展示方案发送邀请按钮',
  [ConfigId.ShowJoinPlanBtn]: '展示加入方案按钮',
  [ConfigId.ShowPlanApplyResultBtn]: '展示方案报名结果页按钮',
  [ConfigId.ShowPlanWithdrawBtn]: '展示方案撤回按钮',
  [ConfigId.ShowPlanCopyBtn]: '展示复制方案按钮',
  [ConfigId.ShowPlanEditBtn]: '展示编辑方案按钮',
  [ConfigId.UsePlanSendInviteDefaultAction]: '使用默认的方案发送邀请动作',
  [ConfigId.UsePlanWithdrawDefaultAction]: '使用默认的方案撤回动作',
  [ConfigId.UsePlanViewDefaultAction]: '使用默认的方案查看动作',
  [ConfigId.NeedCheckGray]: '是否需要灰度鉴权',
  [ConfigId.ApplyDefaultRole]: '活动 CRUD 页权限申请角色',
  [ConfigId.UseNewFrameworkApplyResPage]: '是否使用新的报名结果页面',
  [ConfigId.UseNewZsptFramework]: '是否使用新框架',

  [ConfigId.PlanType]: '方案类型',
  [ConfigId.Env]: '环境',
  [ConfigId.WhiteList]: '白名单',
}
